FROM node:alpine

WORKDIR '/app'

COPY package.json .
RUN npm install

# Copy everything inside the src and public folder and send to the docker container under the /app folder
COPY . .

CMD ["npm", "run", "start"]